import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#1976D2',
    primaryContainer: '#E3F2FD',
    secondary: '#424242',
    secondaryContainer: '#F5F5F5',
    tertiary: '#2E7D32',
    tertiaryContainer: '#E8F5E8',
    error: '#D32F2F',
    errorContainer: '#FFEBEE',
    background: '#FFFFFF',
    surface: '#F8F9FA',
    surfaceVariant: '#F1F3F4',
    outline: '#E0E0E0',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#0D47A1',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#212121',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#1B5E20',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    onBackground: '#1C1B1F',
    onSurface: '#1C1B1F',
    onSurfaceVariant: '#49454F',
  },
  fonts: {
    ...MD3LightTheme.fonts,
    displayLarge: { ...MD3LightTheme.fonts.displayLarge, fontFamily: 'System' },
    displayMedium: { ...MD3LightTheme.fonts.displayMedium, fontFamily: 'System' },
    displaySmall: { ...MD3LightTheme.fonts.displaySmall, fontFamily: 'System' },
    headlineLarge: { ...MD3LightTheme.fonts.headlineLarge, fontFamily: 'System' },
    headlineMedium: { ...MD3LightTheme.fonts.headlineMedium, fontFamily: 'System' },
    headlineSmall: { ...MD3LightTheme.fonts.headlineSmall, fontFamily: 'System' },
    titleLarge: { ...MD3LightTheme.fonts.titleLarge, fontFamily: 'System' },
    titleMedium: { ...MD3LightTheme.fonts.titleMedium, fontFamily: 'System' },
    titleSmall: { ...MD3LightTheme.fonts.titleSmall, fontFamily: 'System' },
    bodyLarge: { ...MD3LightTheme.fonts.bodyLarge, fontFamily: 'System' },
    bodyMedium: { ...MD3LightTheme.fonts.bodyMedium, fontFamily: 'System' },
    bodySmall: { ...MD3LightTheme.fonts.bodySmall, fontFamily: 'System' },
    labelLarge: { ...MD3LightTheme.fonts.labelLarge, fontFamily: 'System' },
    labelMedium: { ...MD3LightTheme.fonts.labelMedium, fontFamily: 'System' },
    labelSmall: { ...MD3LightTheme.fonts.labelSmall, fontFamily: 'System' },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#90CAF9',
    primaryContainer: '#0D47A1',
    secondary: '#B0BEC5',
    secondaryContainer: '#37474F',
    tertiary: '#A5D6A7',
    tertiaryContainer: '#1B5E20',
    error: '#F48FB1',
    errorContainer: '#B71C1C',
    background: '#121212',
    surface: '#1E1E1E',
    surfaceVariant: '#2D2D2D',
    outline: '#424242',
    onPrimary: '#0D47A1',
    onPrimaryContainer: '#E3F2FD',
    onSecondary: '#263238',
    onSecondaryContainer: '#ECEFF1',
    onTertiary: '#1B5E20',
    onTertiaryContainer: '#E8F5E8',
    onError: '#B71C1C',
    onErrorContainer: '#FFEBEE',
    onBackground: '#E0E0E0',
    onSurface: '#E0E0E0',
    onSurfaceVariant: '#CAC4D0',
  },
  fonts: {
    ...MD3DarkTheme.fonts,
    displayLarge: { ...MD3DarkTheme.fonts.displayLarge, fontFamily: 'System' },
    displayMedium: { ...MD3DarkTheme.fonts.displayMedium, fontFamily: 'System' },
    displaySmall: { ...MD3DarkTheme.fonts.displaySmall, fontFamily: 'System' },
    headlineLarge: { ...MD3DarkTheme.fonts.headlineLarge, fontFamily: 'System' },
    headlineMedium: { ...MD3DarkTheme.fonts.headlineMedium, fontFamily: 'System' },
    headlineSmall: { ...MD3DarkTheme.fonts.headlineSmall, fontFamily: 'System' },
    titleLarge: { ...MD3DarkTheme.fonts.titleLarge, fontFamily: 'System' },
    titleMedium: { ...MD3DarkTheme.fonts.titleMedium, fontFamily: 'System' },
    titleSmall: { ...MD3DarkTheme.fonts.titleSmall, fontFamily: 'System' },
    bodyLarge: { ...MD3DarkTheme.fonts.bodyLarge, fontFamily: 'System' },
    bodyMedium: { ...MD3DarkTheme.fonts.bodyMedium, fontFamily: 'System' },
    bodySmall: { ...MD3DarkTheme.fonts.bodySmall, fontFamily: 'System' },
    labelLarge: { ...MD3DarkTheme.fonts.labelLarge, fontFamily: 'System' },
    labelMedium: { ...MD3DarkTheme.fonts.labelMedium, fontFamily: 'System' },
    labelSmall: { ...MD3DarkTheme.fonts.labelSmall, fontFamily: 'System' },
  },
};

export const getTheme = (isDark: boolean) => isDark ? darkTheme : lightTheme;